routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    // return view('welcome');
    return redirect()->route('admin.login');
});

//Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::prefix('admin')->group(function() {
    Route::get('/login', [App\Http\Controllers\Auth\Admin\AdminLoginController::class, 'showLoginForm'])->name('admin.login');
    Route::post('/login', [App\Http\Controllers\Auth\Admin\AdminLoginController::class, 'login'])->name('admin.login.submit');
    Route::post('logout/', [App\Http\Controllers\Auth\Admin\AdminLoginController::class, 'logout'])->name('admin.logout');

    Route::post('/reminder', [App\Http\Controllers\Admin\AdminController::class, 'reminder'])->name('reminder');
    Route::post('/re-reminder', [App\Http\Controllers\Admin\AdminController::class, 'reReminder'])->name('re.reminder');
    Route::get('/dashboard', [App\Http\Controllers\Admin\AdminController::class,'index'])->name('admin.dashboard');
    Route::resource('users', 'App\Http\Controllers\Admin\UserController');
    Route::resource('account', 'App\Http\Controllers\Admin\AccountController');
    Route::post('/account/authentication', [App\Http\Controllers\Admin\AccountController::class, 'customerAuth'])->name('account.authentication');
    Route::post('/account/information', [App\Http\Controllers\Admin\AccountController::class, 'customerInformation'])->name('account.information');
    Route::post('/get/otp', [App\Http\Controllers\Admin\AccountController::class, 'getOtp'])->name('get.otp');


    Route::get('/file-export',[App\Http\Controllers\Admin\AccountController::class,'export'])->name('export');
    Route::get('/file-import',[App\Http\Controllers\Admin\AccountController::class,'importView'])->name('import-view');
    Route::post('/import',[App\Http\Controllers\Admin\AccountController::class,'import'])->name('import');
    Route::get('/download-pdf/{id}',[App\Http\Controllers\Admin\AccountController::class,'downloadPDF'])->name('downloadPDF');
    // Route::get('users', [App\Http\Controllers\Admin\UserController::class, 'index'])->name('users.index');
    // Route::get('users', [App\Http\Controllers\Admin\UserController::class, 'index'])->name('users.index');
    Route::resource('agent', 'App\Http\Controllers\Admin\AgentController');
    Route::resource('bank', 'App\Http\Controllers\Admin\BankController');
    Route::resource('company', 'App\Http\Controllers\Admin\CompanyController');

    Route::post('/get-agent-phone',[App\Http\Controllers\Admin\AccountController::class,'getPhone'])->name('get.phone');
    Route::post('/get-bank-name',[App\Http\Controllers\Admin\AccountController::class,'getBank'])->name('get.bank');

    Route::post('crop-image-before-upload-using-croppie', [App\Http\Controllers\Admin\AccountController::class,'uploadCropImage'])->name('cropimage');
    Route::get('payment-status', [App\Http\Controllers\Admin\AccountController::class,'paymentStatusGet'])->name('payment.status.get');
    Route::post('payment-status', [App\Http\Controllers\Admin\AccountController::class,'paymentStatusPost'])->name('payment.status.post');


    Route::get('revise-payment-notify', [App\Http\Controllers\Admin\AccountController::class,'revisePaymentNotifyGet'])->name('revise.paymentnotify.get');
    Route::post('revise-payment-notify', [App\Http\Controllers\Admin\AccountController::class,'revisePaymentNotifyPost'])->name('revise.payment.notify.post');
    Route::delete('account-delete', [App\Http\Controllers\Admin\AccountController::class,'deleteAccount'])->name('account.delete');


}) ;

app/Models/Bank.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Bank extends Model
{
    use HasFactory;
}

app/Http/Controllers/Admin/BankController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Bank;
use DataTables;

class BankController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if ($request->ajax()) {
            $data = Bank::select('*')->get();
            return Datatables::of($data)
                ->addIndexColumn()
                ->addColumn('action', function($row){
                    $btn = '<a href="'. route('bank.edit', $row->id) .'" data-toggle="tooltip" data-original-title="Edit"> <i class="fa fa-pencil text-inverse m-r-10"></i> </a> ';
                    return $btn;
                })
                ->addColumn('status', function($row){
                            if($row->status) {
                                $status = '<a data-toggle="tooltip" data-placement="left" data-original-title=" Active Status" class="label label-info" style="color:#f0f0f0;" aria-describedby="tooltip659663">Active</a>';
                            } else {
                                $status = '<a data-toggle="tooltip" data-placement="left" data-original-title=" In Active" class="label label-danger" style="color:#f0f0f0;" aria-describedby="tooltip659663">In Active</a>';
                            }
                            return $status;
                })
                ->escapeColumns('status')
                ->rawColumns(['action'])
                ->make(true);

        }
        
        return view('admin.banks.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.banks.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $bank = new Bank();
        $bank->name = $request->get('name');
        $bank->branch  = $request->get('branch');
        $bank->status  = 1;
        $bank->save();

        return redirect()->route('bank.index')
                         ->with('message','Insert record successfully')
                         ->with('message_type','success');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $bank = Bank::find($id);
        return view('admin.banks.edit',compact('bank'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $bank = Bank::find($id);
        $bank->name = $request->get('name');
        $bank->branch  = $request->get('branch');
        $bank->status  = 1;
        $bank->save();

        return redirect()->route('bank.index')
                         ->with('message','Update record successfully')
                         ->with('message_type','success');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/banks/create.blade.php
@extends('admin.layouts.layout')
@section('content')
<div class="row page-titles">
    <div class="col-md-5 align-self-center">
        <h3 class="text-themecolor">Banks</h3>
    </div>
    <div class="col-md-7 align-self-center">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="javascript:void(0)">Home</a></li>
            <li class="breadcrumb-item active">Banks </li>
            <li class="breadcrumb-item active">Create</li>
        </ol>
    </div>
</div>
<div class="container-fluid">
    <div class="row">
        <div class="col-lg-12">
            <div class="card card-outline-info">
                <div class="card-header">
                    <h4 class="m-b-0 text-white">Create Bank</h4>
                </div>
                <div class="card-body">
                	{{ Form::open(array('url' => 'admin/bank', 'method' => 'post','class' =>'')) }}
                	@csrf  
                	<div class="row col-md-12">
				        <div class="col-md-6">
				            <div class="form-group @if($errors->has('name')) has-danger @endif">
				                <label class="control-label">Bank Name</label>
				                <?=Form::text('name', old('name'), ['class' => 'form-control form-control-sm', 'placeholder' => 'Enter Bank Name'])?>
				                <span class='text-danger error'>{{ $errors->first('name') }}</span>
				            </div>
				        </div>
						<div class="col-md-6">
				           <div class="form-group @if($errors->has('branch'))has-danger @endif">
				                <label class="control-label">Branch Name</label>
				                <?=Form::text('branch', old('branch'), ['class' => 'form-control form-control-sm', 'placeholder' => 'Enter Branch Name'])?>
				                <span class='text-danger error'>{{ $errors->first('branch') }}</span>
				            </div>
				        </div>
				    </div>
				    <!--/row-->
					<div class="form-actions">
					    <button type="submit" class="btn btn-success" value="exit" name="save"> <i class="fa fa-check"></i> Save</button>
					    <button type="submit" class="btn btn-success"> <i class="fa fa-check"></i> Save & New</button>
					    <a data-showloading="yes" href="{{route('bank.index')}}" class="btn btn-inverse">Cancel</a>
					   
					</div>
                    <?=Form::close();?>
                </div>
            </div>
        </div>
    </div>
</div>
@stop

@section('style')
@stop

@section('script')
@include('admin.layouts.alert')
@stop

resources/views/admin/banks/edit.blade.php
@extends('admin.layouts.layout')
@section('content')
<div class="row page-titles">
    <div class="col-md-5 align-self-center">
        <h3 class="text-themecolor">Bank</h3>
    </div>
    <div class="col-md-7 align-self-center">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="javascript:void(0)">Home</a></li>
            <li class="breadcrumb-item active">Bank </li>
            <li class="breadcrumb-item active">Create</li>
        </ol>
    </div>
</div>
<div class="container-fluid">
    <div class="row">
        <div class="col-lg-12">
        	<div class="card card-outline-info">
                <div class="card-header">
                    <h4 class="m-b-0 text-white">Edit Bank</h4>
                </div>
                <div class="card-body">
                	{!! Form::model($bank, [
					   'method' => 'PATCH',
					    'route' => ['bank.update', $bank->id]
					,'files' => true]) !!}
                	@csrf
                	<div class="row col-md-12">
				        <div class="col-md-6">
				            <div class="form-group @if($errors->has('name')) has-danger @endif">
				                <label class="control-label">Bank Name</label>
				                <?=Form::text('name', old('name'), ['class' => 'form-control form-control-sm', 'placeholder' => 'Enter Bank Name'])?>
				                <span class='text-danger error'>{{ $errors->first('name') }}</span>
				            </div>
				        </div>
						<div class="col-md-6">
				           <div class="form-group @if($errors->has('branch'))has-danger @endif">
				                <label class="control-label">Branch Name</label>
				                <?=Form::text('branch', old('branch'), ['class' => 'form-control form-control-sm', 'placeholder' => 'Enter Branch Name'])?>
				                <span class='text-danger error'>{{ $errors->first('branch') }}</span>
				            </div>
				        </div>
				    </div>
                	<div class="form-actions p-20">
					    <button type="submit" class="btn btn-success" value="exit" name="save"> <i class="fa fa-check"></i> Save</button>
					    <a data-showloading="yes" href="{{route('bank.index')}}" class="btn btn-inverse">Cancel</a>
					   
					</div>
                    <?=Form::close();?>
                </div>
            </div>
        	
        </div>
    </div>
</div>
@stop

@section('css')
  
@stop

@section('script')
   
@include('admin.layouts.alert')
@stop

resources/views/admin/banks/index.blade.php
@extends('admin.layouts.layout')
@section('content')
<div class="row page-titles">
    <div class="col-md-5 align-self-center">
        <h3 class="text-themecolor">Banks</h3>
    </div>
    <div class="col-md-7 align-self-center">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="javascript:void(0)">Home</a></li>
            <li class="breadcrumb-item active">Bank list</li>
        </ol>
    </div>
    <div>
        <button class="right-side-toggle waves-effect waves-light btn-inverse btn btn-circle btn-sm pull-right m-l-10"><i class="ti-settings text-white"></i></button>
    </div>
</div>
<div class="container-fluid">
    <!-- ============================================================== -->
    <!-- Start Page Content -->
    <!-- ============================================================== -->
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <div class="card">
                        <div class="card-body">
                        <div class="text-right">
                            <a href="{{route('bank.create')}}" class="btn waves-effect waves-light btn-info" title="Add New">Add New</a>
                        </div>
                        <div class="table-responsive m-t-20">
                        <table id="master_table" class="table table-bordered table-striped data-table">
                            <thead>
                                <tr>
                                    <th>No</th>
                                    <th>Name</th>
                                    <th>Branch</th>
                                    <th>Status</th>
                                    <th width="100px">Action</th>
                                </tr>
                            </thead>
                        </table>
                        </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@stop

@section('script')
<script src="{{asset('/backend/js/plugins/jquery.dataTables.min.js')}}"></script>
<script src="{{asset('/backend/js/plugins/jquery.dataTables.min.js')}}"></script>
<script src="{{asset('backend/js/delete_script.js')}}"></script>
<script src="{{asset('backend/plugins/sweetalert/sweetalert.min.js')}}"></script>
<script src="{{asset('backend/js/fnStandingRedraw.js')}}"></script>
<!-- public/backend/plugins/sweetalert -->
<script type="text/javascript">
$(function () {
    
    var table = $('.data-table').DataTable({
        processing: true,
        serverSide: true,
        ajax: "{{ route('bank.index') }}",
        columns: [
            {data: 'id', name: 'id'},
            {data: 'name', name: 'name'},
            {data: 'branch', name: 'branch'},
            {data: 'status', name: 'status'},
            {data: 'action', name: 'action', orderable: false, searchable: false},
        ]
    });
    
  });
</script>
@include('admin.layouts.alert')
@stop

<!-- 
<!DOCTYPE html>
<html>
<head>
    <title>Laravel 8 Datatables Tutorial - ItSolutionStuff.com</title>
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css" />
    <link href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css" rel="stylesheet">
    <link href="https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap4.min.css" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.js"></script>  
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.0/jquery.validate.js"></script>
    <script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap4.min.js"></script>
</head>
<body>
    
<div class="container">
    <h1>Laravel 8 Datatables Tutorial <br/> ItSolutionStuff.com</h1>
    <table class="table table-bordered data-table">
        <thead>
            <tr>
                <th>No</th>
                <th>Name</th>
                <th>Email</th>
                <th width="100px">Action</th>
            </tr>
        </thead>
        <tbody>
        </tbody>
    </table>
</div>
   
</body>
   
<script type="text/javascript">
  $(function () {
    
    var table = $('.data-table').DataTable({
        processing: true,
        serverSide: true,
        ajax: "{{ route('users.index') }}",
        columns: [
            {data: 'id', name: 'id'},
            {data: 'name', name: 'name'},
            {data: 'email', name: 'email'},
            {data: 'action', name: 'action', orderable: false, searchable: false},
        ]
    });
    
  });
</script>
</html> -->