routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    // return view('welcome');
    return redirect()->route('admin.login');
});

//Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::prefix('admin')->group(function() {
    Route::get('/login', [App\Http\Controllers\Auth\Admin\AdminLoginController::class, 'showLoginForm'])->name('admin.login');
    Route::post('/login', [App\Http\Controllers\Auth\Admin\AdminLoginController::class, 'login'])->name('admin.login.submit');
    Route::post('logout/', [App\Http\Controllers\Auth\Admin\AdminLoginController::class, 'logout'])->name('admin.logout');

    Route::post('/reminder', [App\Http\Controllers\Admin\AdminController::class, 'reminder'])->name('reminder');
    Route::post('/re-reminder', [App\Http\Controllers\Admin\AdminController::class, 'reReminder'])->name('re.reminder');
    Route::get('/dashboard', [App\Http\Controllers\Admin\AdminController::class,'index'])->name('admin.dashboard');
    Route::resource('users', 'App\Http\Controllers\Admin\UserController');
    Route::resource('account', 'App\Http\Controllers\Admin\AccountController');
    Route::post('/account/authentication', [App\Http\Controllers\Admin\AccountController::class, 'customerAuth'])->name('account.authentication');
    Route::post('/account/information', [App\Http\Controllers\Admin\AccountController::class, 'customerInformation'])->name('account.information');
    Route::post('/get/otp', [App\Http\Controllers\Admin\AccountController::class, 'getOtp'])->name('get.otp');


    Route::get('/file-export',[App\Http\Controllers\Admin\AccountController::class,'export'])->name('export');
    Route::get('/file-import',[App\Http\Controllers\Admin\AccountController::class,'importView'])->name('import-view');
    Route::post('/import',[App\Http\Controllers\Admin\AccountController::class,'import'])->name('import');
    Route::get('/download-pdf/{id}',[App\Http\Controllers\Admin\AccountController::class,'downloadPDF'])->name('downloadPDF');
    // Route::get('users', [App\Http\Controllers\Admin\UserController::class, 'index'])->name('users.index');
    // Route::get('users', [App\Http\Controllers\Admin\UserController::class, 'index'])->name('users.index');
    Route::resource('agent', 'App\Http\Controllers\Admin\AgentController');
    Route::resource('bank', 'App\Http\Controllers\Admin\BankController');
    Route::resource('company', 'App\Http\Controllers\Admin\CompanyController');

    Route::post('/get-agent-phone',[App\Http\Controllers\Admin\AccountController::class,'getPhone'])->name('get.phone');
    Route::post('/get-bank-name',[App\Http\Controllers\Admin\AccountController::class,'getBank'])->name('get.bank');

    Route::post('crop-image-before-upload-using-croppie', [App\Http\Controllers\Admin\AccountController::class,'uploadCropImage'])->name('cropimage');
    Route::get('payment-status', [App\Http\Controllers\Admin\AccountController::class,'paymentStatusGet'])->name('payment.status.get');
    Route::post('payment-status', [App\Http\Controllers\Admin\AccountController::class,'paymentStatusPost'])->name('payment.status.post');


    Route::get('revise-payment-notify', [App\Http\Controllers\Admin\AccountController::class,'revisePaymentNotifyGet'])->name('revise.paymentnotify.get');
    Route::post('revise-payment-notify', [App\Http\Controllers\Admin\AccountController::class,'revisePaymentNotifyPost'])->name('revise.payment.notify.post');
    Route::delete('account-delete', [App\Http\Controllers\Admin\AccountController::class,'deleteAccount'])->name('account.delete');


}) ;

resources/views/admin/layouts/alert.blade.php
@if(Session::has('message'))
	@if(Session::get('message_type'))
		<script>
	        $(document).ready(function(){
		        toastr.{{ Session::get('message_type') }}
		        ('{{ Session::get('message') }}');
	        });
	    </script>
    @endif
@endif

@if ($errors->any())

<script type="text/javascript">
	$(document).ready(function(){
        toastr.error
        ("<b>There were some errors.</b>");
	});
</script>
@endif

resources/views/admin/layouts/footer.blade.php
    
    <!-- ============================================================== -->
    <script src="{{asset('/backend/js/jquery/jquery.min.js')}}"></script>
    <!-- Bootstrap tether Core JavaScript -->
    <script src="{{asset('/backend/js/bootstrap/popper.min.js')}}"></script>

    <script src="{{asset('/backend/js/bootstrap/bootstrap.min.js')}}"></script>
    <!-- slimscrollbar scrollbar JavaScript -->
    <script src="{{asset('/backend/js/jquery.slimscroll.js')}}"></script>
    <!--Wave Effects -->
    <script src="{{asset('/backend/js/waves.js')}}"></script>
    <!--Menu sidebar -->
    <script src="{{asset('/backend/js/sidebarmenu.js')}}"></script>
    <!--stickey kit -->
    <script src="{{asset('/backend/js/plugins/sticky-kit.min.js')}}"></script>
    <script src="{{asset('/backend/js/plugins/jquery.sparkline.min.js')}}"></script>
    <!--Custom JavaScript -->
    <script src="{{asset('/backend/js/custom.min.js')}}"></script>
    <script src="{{asset('/backend/js/toastr.js')}}"></script>
    <!-- ============================================================== -->
    <!-- Style switcher -->
    <!-- ============================================================== -->
   
    <script src="{{asset('/backend/js/plugins/jQuery.style.switcher.js')}}"></script>
    <script src="{{asset('/backend/plugins/toast-master/js/toastr.min.js')}}"></script>
    <script src="{{asset('/backend/js/plugins/dashboard1.js')}}"></script>
    <script src="{{asset('/backend/js/plugins/morris.min.js')}}"></script>
    <script src="{{asset('/backend/js/plugins/raphael-min.js')}}"></script>

resources/views/admin/layouts/header.blade.php
<header class="topbar">
    <nav class="navbar top-navbar navbar-expand-md navbar-light">
        <!-- ============================================================== -->
        <!-- Logo -->
        <!-- ============================================================== -->
        <div class="navbar-header">
            <a class="navbar-brand" href="#">
                <!-- Logo icon --><b>
                    <!--You can put here icon as well // <i class="wi wi-sunset"></i> //-->
                    <!-- Dark Logo icon -->
                    <img src="{{URL::asset('/backend/images/small.jpg')}}" alt="mkvfinance" class="dark-logo" />
                    <!-- Light Logo icon -->
                    <img src="{{URL::asset('/backend/images/logo-text.png')}}" alt="mkvfinance" class="light-logo" />
                </b>
                <!--End Logo icon -->
                <!-- Logo text --><span>
                <!-- dark Logo text -->
                <img src="{{URL::asset('/backend/images/big1.jpg')}}" alt="homepage" class="dark-logo" />
                <!-- Light Logo text -->    
                <img src="{{URL::asset('/backend/images/logo-light-text.png')}}" class="light-logo" alt="homepage" /></span> </a>
        </div>
        <!-- ============================================================== -->
        <!-- End Logo -->
        <!-- ============================================================== -->
        <div class="navbar-collapse">
            <!-- ============================================================== -->
            <!-- toggle and nav items -->
            <!-- ============================================================== -->
            <ul class="navbar-nav mr-auto mt-md-0">
                <!-- This is  -->
                <li class="nav-item"> <a class="nav-link nav-toggler hidden-md-up text-muted waves-effect waves-dark" href="javascript:void(0)"><i class="mdi mdi-menu"></i></a> </li>
                <li class="nav-item m-l-10"> <a class="nav-link sidebartoggler hidden-sm-down text-muted waves-effect waves-dark" href="javascript:void(0)"><i class="ti-menu"></i></a> </li>
                <!-- ============================================================== -->
         
            </ul>
            <!-- ============================================================== -->
            <!-- User profile and search -->
            <!-- ============================================================== -->
            <ul class="navbar-nav my-lg-0">
                <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle text-muted waves-effect waves-dark" href="" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <span class="fa fa-cog " style="font-size: 2em;"></span>
                        </a>
                        <div class="dropdown-menu dropdown-menu-right scale-up">
                            <ul class="dropdown-user">
                                <li>
                                    <div class="dw-user-box">
                                        <i class="fa fa-user-o" aria-hidden="true"></i>
                                        <div class="u-text">
                                            <h4>{{ ucfirst(Auth::guard('admin')->user()->name) }}</h4>
                                            <p class="text-muted">{{ ucfirst(Auth::guard('admin')->user()->email) }}</p>
                                        </div>
                                    </div>
                                </li>
                                <!-- <li role="separator" class="divider"></li> -->
                                <!-- <li>
                                    <a href="#" class="some other  classes" admin="1"><span class="ti-user"> </span> My Profile</a>
                                </li>
                                <li role="separator" class="divider"></li>
                                <li>
                                    <a href="#" class="some other  classes"><span class="fa fa-key "> </span> Change Password</a>
                                </li> -->
                                <li role="separator" class="divider"></li>
                                <li>
                                <a href="{{ route('admin.logout') }}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();"><i class="fa fa-power-off"></i> Logout</a>

                                <form id="logout-form" action="{{ route('admin.logout') }}" method="POST" style="display: none;">{{ csrf_field() }}</form>
                                    
                                </li>
                            </ul>
                        </div>
                    </li>
            </ul>
        </div>
    </nav>
</header>

resources/views/admin/layouts/layout.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <!-- Favicon icon -->
    <link rel="icon" type="image/png" sizes="16x16" href="/frontend/images/2-1.png">
    <title>Welcome to Mkv Finance</title>
    <!-- Bootstrap Core CSS -->

    <link rel="stylesheet" type="text/css" href="{{asset('backend/css/bootstrap/bootstrap.min.css')}}">
    <!-- Custom CSS -->
    <link rel="stylesheet" type="text/css" href="{{asset('backend/css/style.css')}}">
    <!-- You can change the theme colors from here -->
    <link rel="stylesheet" type="text/css" href="{{asset('backend/css/colors/blue.css')}}">
    <link rel="stylesheet" type="text/css" href="{{asset('backend/plugins/toast-master/css/toastr.min.css')}}">
    <link rel="stylesheet" type="text/css" href="{{asset('backend/plugins/sweetalert/sweetalert.css')}}">
    <link rel="stylesheet" type="text/css" href="{{asset('backend/css/fileupload/bootstrap-fileupload.css')}}">
    <link rel="stylesheet" type="text/css" href="{{asset('backend/css/plugin/morris.css')}}">
    @yield('css')



    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
<![endif]-->
</head>

<body class="fix-header card-no-border">
   
    <!-- ============================================================== -->
    <!-- Main wrapper - style you can find in pages.scss -->
    <!-- ============================================================== -->
    <div class="preloader">
       <svg class="circular" viewBox="25 25 50 50">
          <circle class="path" cx="50" cy="50" r="20" fill="none" stroke-width="2" stroke-miterlimit="10"></circle>
       </svg>
    </div>
    <div id="main-wrapper">
        <!-- ============================================================== -->
       	@include('admin.layouts.header')
       	@include('admin.layouts.sidebar')

        <!-- Page wrapper  -->
         <div class="page-wrapper">

            
                @yield('content')
          

            <footer class="footer">
            Copyright© {{ date('Y')}} MKV Finance
            </footer>
            
        </div>
    </div>
   
    @include('admin.layouts.footer')
    @yield('script')
    @yield('modal')
</body>

</html>

resources/views/admin/layouts/sidebar.blade.php
<aside class="left-sidebar">
            <!-- Sidebar scroll-->
    <div class="scroll-sidebar">
        <!-- Sidebar navigation-->
        <nav class="sidebar-nav">
            <ul id="sidebarnav">
                <!-- <li class="nav-devider"></li> -->
                <li> 
                    <a class="waves-effect waves-dark" href="{{route('admin.dashboard')}}" aria-expanded="false"><i class="mdi mdi-gauge"></i><span class="hide-menu">Dashboard</span></a>
                </li>
                <li> 
                    <a class="has-arrow waves-effect waves-dark" href="#" aria-expanded="false"><i class="mdi mdi-microsoft"></i><span class="hide-menu">User Management<span class="label label-rouded label-themecolor pull-right">1</span></span></a>
                    <ul aria-expanded="false" class="collapse {{ (request()->is('admin/account/*')) ? 'in' : '' }} ">
                        <!-- <li><a class="waves-effect" href="{{route('users.index')}}"><i class="fa fa-pencil-square-o" aria-hidden="true"></i><span> Users </span></a></li> -->   
                        <li class="{{ (request()->is('admin/account/*')) ? 'active' : '' }}"><a class="waves-effect {{ (request()->is('admin/account/*')) ? 'active' : '' }}" href="{{route('account.index')}}"><i class="fa fa-pencil-square-o" aria-hidden="true"></i><span> Users </span></a></li>
                    </ul>                     
                </li>
                <li> 
                    <a class="has-arrow waves-effect waves-dark" href="#" aria-expanded="false"><i class="mdi mdi-microsoft"></i><span class="hide-menu">Master<span class="label label-rouded label-themecolor pull-right">3</span></span></a>
                    <ul aria-expanded="false" class="collapse {{ (request()->is('admin/agent/*')) ? 'in' : '' }} ">
                        <!-- <li><a class="waves-effect" href="{{route('users.index')}}"><i class="fa fa-pencil-square-o" aria-hidden="true"></i><span> Users </span></a></li> -->   
                        <li class="{{ (request()->is('admin/agent/*')) ? 'active' : '' }}"><a class="waves-effect {{ (request()->is('admin/agent/*')) ? 'active' : '' }}" href="{{route('agent.index')}}"><i class="fa fa-pencil-square-o" aria-hidden="true"></i><span> Agents </span></a></li>
                        <li class="{{ (request()->is('admin/bank/*')) ? 'active' : '' }}"><a class="waves-effect {{ (request()->is('admin/bank/*')) ? 'active' : '' }}" href="{{route('bank.index')}}"><i class="fa fa-pencil-square-o" aria-hidden="true"></i><span> Banks </span></a></li>
                        <li class="{{ (request()->is('admin/company/*')) ? 'active' : '' }}"><a class="waves-effect {{ (request()->is('admin/company/*')) ? 'active' : '' }}" href="{{route('company.index')}}"><i class="fa fa-pencil-square-o" aria-hidden="true"></i><span> Company </span></a></li>
                    </ul>                     
                </li>               
            </ul>
        </nav>
        <!-- End Sidebar navigation -->
    </div>
    <!-- End Sidebar scroll-->
</aside>