routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    // return view('welcome');
    return redirect()->route('admin.login');
});

//Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::prefix('admin')->group(function() {
    Route::get('/login', [App\Http\Controllers\Auth\Admin\AdminLoginController::class, 'showLoginForm'])->name('admin.login');
    Route::post('/login', [App\Http\Controllers\Auth\Admin\AdminLoginController::class, 'login'])->name('admin.login.submit');
    Route::post('logout/', [App\Http\Controllers\Auth\Admin\AdminLoginController::class, 'logout'])->name('admin.logout');

    Route::post('/reminder', [App\Http\Controllers\Admin\AdminController::class, 'reminder'])->name('reminder');
    Route::post('/re-reminder', [App\Http\Controllers\Admin\AdminController::class, 'reReminder'])->name('re.reminder');
    Route::get('/dashboard', [App\Http\Controllers\Admin\AdminController::class,'index'])->name('admin.dashboard');
    Route::resource('users', 'App\Http\Controllers\Admin\UserController');
    Route::resource('account', 'App\Http\Controllers\Admin\AccountController');
    Route::post('/account/authentication', [App\Http\Controllers\Admin\AccountController::class, 'customerAuth'])->name('account.authentication');
    Route::post('/account/information', [App\Http\Controllers\Admin\AccountController::class, 'customerInformation'])->name('account.information');
    Route::post('/get/otp', [App\Http\Controllers\Admin\AccountController::class, 'getOtp'])->name('get.otp');


    Route::get('/file-export',[App\Http\Controllers\Admin\AccountController::class,'export'])->name('export');
    Route::get('/file-import',[App\Http\Controllers\Admin\AccountController::class,'importView'])->name('import-view');
    Route::post('/import',[App\Http\Controllers\Admin\AccountController::class,'import'])->name('import');
    Route::get('/download-pdf/{id}',[App\Http\Controllers\Admin\AccountController::class,'downloadPDF'])->name('downloadPDF');
    // Route::get('users', [App\Http\Controllers\Admin\UserController::class, 'index'])->name('users.index');
    // Route::get('users', [App\Http\Controllers\Admin\UserController::class, 'index'])->name('users.index');
    Route::resource('agent', 'App\Http\Controllers\Admin\AgentController');
    Route::resource('bank', 'App\Http\Controllers\Admin\BankController');
    Route::resource('company', 'App\Http\Controllers\Admin\CompanyController');

    Route::post('/get-agent-phone',[App\Http\Controllers\Admin\AccountController::class,'getPhone'])->name('get.phone');
    Route::post('/get-bank-name',[App\Http\Controllers\Admin\AccountController::class,'getBank'])->name('get.bank');

    Route::post('crop-image-before-upload-using-croppie', [App\Http\Controllers\Admin\AccountController::class,'uploadCropImage'])->name('cropimage');
    Route::get('payment-status', [App\Http\Controllers\Admin\AccountController::class,'paymentStatusGet'])->name('payment.status.get');
    Route::post('payment-status', [App\Http\Controllers\Admin\AccountController::class,'paymentStatusPost'])->name('payment.status.post');


    Route::get('revise-payment-notify', [App\Http\Controllers\Admin\AccountController::class,'revisePaymentNotifyGet'])->name('revise.paymentnotify.get');
    Route::post('revise-payment-notify', [App\Http\Controllers\Admin\AccountController::class,'revisePaymentNotifyPost'])->name('revise.payment.notify.post');
    Route::delete('account-delete', [App\Http\Controllers\Admin\AccountController::class,'deleteAccount'])->name('account.delete');


}) ;

app/Models/Account.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Carbon\Carbon;
use Illuminate\Database\Eloquent\SoftDeletes;

class Account extends Model
{

    use SoftDeletes;
    use HasFactory;
     protected $dates = ['deleted_at'];  
    protected $fillable = ['company_id','name', 'email', 'mobile', 'otp', 'aadhaar_card', 'pan_card' ,'passport_card', 'photo', 'other', 'agent_name', 'agent_mobile', 'bank_name', 'branch', 'fund', 'charge','finance_rate', 'finance_duration', 'finance_date','type', 'is_verify', 'note', 'remind_date', 'payment_status','pay_option','revise_remind'];

    public function setFinanceDateAttribute($value) {
      $this->attributes['finance_date'] = Carbon::createFromFormat('m-d-Y',$value)->format('Y-m-d');
    }

    public function getFinanceDateAttribute($value) {
        return Carbon::parse($value)->format('m-d-Y');
    }
    public function getRemindDateAttribute($value) {
        return Carbon::parse($value)->format('m-d-Y');
    }

    public function setReviseRemindAttribute($value) {
      $this->attributes['revise_remind'] = Carbon::createFromFormat('m-d-Y',$value)->format('Y-m-d');
    }

    public function getReviseRemindAttribute($value) {
        return Carbon::parse($value)->format('m-d-Y');
    }

    /**
     * Get the company associated with the Account.
     */
    public function company()
    {
         return $this->belongsTo(Company::class, 'company_id');
    }
    /**
     * Get the agent associated with the Account.
     */
    public function agent()
    {
         return $this->belongsTo(Agent::class, 'agent_name');
    }
    /**
     * Get the bank associated with the Account.
     */
    public function bank()
    {
         return $this->belongsTo(Bank::class, 'bank_name');
    }
}

app/Http/Controllers/Admin/AccountController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\User;
use App\Models\Account;
use App\Models\Agent;
use App\Models\Company;
use App\Models\Bank;
use DataTables;
use Hash;
use Carbon\Carbon;
use App\Mail\OtpEmail;
use Maatwebsite\Excel\Facades\Excel;
use App\Imports\ImportAccount;
use App\Exports\AccountExport;
use PDF;
Use Image;

class AccountController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if ($request->ajax()) {
            $data = Account::select('*');
            return Datatables::of($data)
                    ->addIndexColumn()
                    ->addColumn('action', function($row){
     
                           $btn = '<a href="'. route('account.edit', $row->id) .'" data-toggle="tooltip" data-original-title="Edit"> <i class="fa fa-pencil text-inverse m-r-10"></i> </a> <a href="'. route('account.show', $row->id) .'" data-toggle="tooltip" data-original-title="View"> <i class="fa fa-eye text-inverse m-r-10"></i> </a> <a href="#" data-account_id="'.$row->id.'" class="update_payment_status" data-toggle="tooltip" data-original-title="View"> <i class="fa fa-cog text-inverse m-r-10"></i> </a> <a href="#" data-account_id="'.$row->id.'" class="revise_payment_notify" data-toggle="tooltip" data-original-title="Update Payment Option"> <i class="fa fa-bank text-inverse m-r-10"></i> </a> <a href="#" onClick=deleteacc("'.$row->id.'") data-account_id="'.$row->id.'" class="deleteacc" data-toggle="tooltip" data-original-title="Delete"> <i class="fa fa-trash text-inverse m-r-10"></i> </a>';
    
                            return $btn;
                    })
                    ->addColumn('created_at', function($row){
                           $btn = date('d-m-Y H:i:s', strtotime($row->created_at));
    
                            return $btn;
                    })
                    ->addColumn('verify', function($row){
                            if($row->is_verify) {
                                $verify = '<span class="badge badge-info">Verified</span>';
                            } else {
                                $verify = '<span class="badge badge-warning">Not verified</span>';
                            }
                            return $verify;
                    })
                    ->addColumn('payment_status', function($row){
                            if($row->payment_status == 0) {
                                $payment_status = '<span class="badge badge-warning">Un Paid</span>';
                            } elseif($row->payment_status == 1) {
                                $payment_status = '<span class="badge badge-success">Paid</span>';
                            } elseif($row->payment_status == 2) {
                                $payment_status = '<span class="badge badge-info">By Pass</span>';
                            }
                            return $payment_status;
                    })
                    ->addColumn('agent_name', function($row){
                            return $row->agent->name ?? "-";
                    })
                    ->addColumn('status', function($row){
                            if($row->status) {
                                $status = '<a data-toggle="tooltip" data-placement="left" data-original-title=" Completed Status" class="label label-primary" style="color:#f0f0f0;" aria-describedby="tooltip659663">Completed</a>';
                            } else {
                                $status = '<a data-toggle="tooltip" data-placement="left" data-original-title=" In Progress Status" class="label label-danger" style="color:#f0f0f0;" aria-describedby="tooltip659663">In Progress</a>';
                            }
                            return $status;
                    })
                    ->escapeColumns('verify', 'status','payment_status')
                    ->rawColumns(['action', 'created_at',' status'])
                    ->make(true);
        }
        
        return view('admin.accounts.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.accounts.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $account = Account::where('id',$id)->first();
        
        return view('admin.accounts.show',compact('account'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $account = Account::where('id',$id)->first();
        $agents = Agent::where('status' ,1)->pluck('name','id',)->toArray();
        $companies = Company::where('status' ,1)->pluck('name','id',)->toArray();
        $banks = Bank::where('status' ,1)->pluck('name','id',)->toArray();
        // dd($account);
         // $p = Carbon::createFromFormat('Y-m-d', $account->finance_date)->format('m-d-Y');; 
         // $account->finance_date = $p;
         // dd($account->company);
        return view('admin.accounts.edit',compact('account','agents', 'companies', 'banks'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        // dd($request->all());
        // dd(Carbon::parse('2019-01-12'));

        $this->validate($request,[
            'company_id'=>'required',
            'name'=>'required',
            'agent_name'=>'required',
            'agent_mobile'=>'required',
            'bank_name'=>'required',
            'branch'=>'required',
        ]);
        
        $account = Account::where('id',$id)->first();
        // $dirPath = public_path('images/'.$id.'/'); 
        // if (!file_exists($dirPath)) {
        //     mkdir($dirPath, 0777, true);
        // }
        // $aadhaarFile = null;
        // if (request()->hasFile('aadhaar_card')) {
        //     $file = request()->file('aadhaar_card');
        //     $aadhaarFile = md5($file->getClientOriginalName() . time()) . "." . $file->getClientOriginalExtension();
        //     // open an image file
        //     $file = \Image::make($file->getRealPath())->resize(400, 300);
       
        //     // $file->move($dirPath, $aadhaarFile);   
        //     $file->save($dirPath.$aadhaarFile);
        //     $account->aadhaar_card = $aadhaarFile;
        //     // die("check");
        // }        
        // $pancardFile = null;
        // if (request()->hasFile('pan_card')) {
        //     $file = request()->file('pan_card');
        //     $pancardFile = md5($file->getClientOriginalName() . time()) . "." . $file->getClientOriginalExtension();
        //     $file = \Image::make($file->getRealPath())->resize(400, 300);
        //     $file->save($dirPath.$pancardFile);
        //     //$file->move($dirPath, $pancardFile);    
        //     $account->pan_card = $pancardFile;
        // }
        // $passportFile = null;
        // if (request()->hasFile('passport_card')) {
        //     $file = request()->file('passport_card');
        //     $passportFile = md5($file->getClientOriginalName() . time()) . "." . $file->getClientOriginalExtension();
        //     $file = \Image::make($file->getRealPath())->resize(400, 300);
        //     $file->save($dirPath.$passportFile);
        //     // $file->move($dirPath, $passportFile);    
        //     $account->passport_card = $passportFile;
        // } 
        // $photoFile = null;
        // if (request()->hasFile('photo')) {
        //     $file = request()->file('photo');
        //     $photoFile = md5($file->getClientOriginalName() . time()) . "." . $file->getClientOriginalExtension();
        //     $file = \Image::make($file->getRealPath())->resize(400, 300);
        //     $file->save($dirPath.$photoFile);
        //     // $file->move($dirPath, $photoFile);    
        //     $account->photo = $photoFile;
        // }
        // $otherFile = null;
        // if (request()->hasFile('other')) {
        //     $file = request()->file('other');
        //     $otherFile = md5($file->getClientOriginalName() . time()) . "." . $file->getClientOriginalExtension();
        //     $file = \Image::make($file->getRealPath())->resize(400, 300);
        //     $file->save($dirPath.$otherFile);
        //     // $file->move($dirPath, $otherFile);    
        //     $account->other = $otherFile;
        // }
        // dd($request->all());
        $account->company_id = $request->get('company_id');
        $account->name = $request->get('name');
        $account->agent_name = $request->get('agent_name');
        $account->agent_mobile = $request->get('agent_mobile');
        $account->other_mobile = $request->get('other_mobile');
        $account->bank_name = $request->get('bank_name');
        $account->branch = $request->get('branch');
        $account->fund = $request->get('fund');
        $account->charge = $request->get('charge');
        $account->finance_date = $request->get('finance_date');
        $account->finance_rate = $request->get('finance_rate');
        $account->finance_duration = $request->get('finance_duration');
        $account->type = $request->get('type');
        $account->note = $request->get('note');
        $account->other_mobile = $request->get('other_mobile');

resources/views/admin/accounts/create.blade.php
@extends('admin.layouts.layout')
@section('content')
<div class="row page-titles">
    <div class="col-md-5 align-self-center">
        <h3 class="text-themecolor">User</h3>
    </div>
    <div class="col-md-7 align-self-center">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="javascript:void(0)">Home</a></li>
            <li class="breadcrumb-item active">Users </li>
            <li class="breadcrumb-item active">Create</li>
        </ol>
    </div>
</div>
<div class="container-fluid">
    <div class="row">
        <div class="col-lg-12">
        	<div class="card card-outline-info">
                <div class="card-header">
                    <h4 class="m-b-0 text-white">Create User</h4>
                </div>
                <?php $show = false;?>
                @if(session()->has('pn'))
			    	<?php
			    	$show = true;
			    	?>
				@endif
                <div class="card-body">
                	{{ Form::open(array('route' => ('account.authentication'), 'method' => 'post','class' =>'')) }}
                	@csrf  
                	<input name="id" type="hidden" value="{{ old('id') }}" class="hiddenID">
                    <div class="row p-t-20">
				        <div class="col-md-6">
				            <div class="form-group @if($errors->has('mobile')) has-danger @endif">
				                <label class="control-label">Phone Number *</label>
				                <?=Form::text('mobile', old('mobile'), ['class' => 'form-control', 'placeholder' => 'Enter Phone Number','required'])?>
				                <span class='text-danger error'>{{ $errors->first('mobile') }}</span>
				            </div>
				        </div>
						<div class="col-md-6">
				           <div class="form-group @if($errors->has('email'))has-danger @endif">
				                <label class="control-label">Email *</label>
				                <?=Form::text('email', old('email'), ['class' => 'form-control', 'placeholder' => 'Enter email','required'])?>
				                <span class='text-danger error'>{{ $errors->first('email') }}</span>
				            </div>
				        </div>
				        <div class="col-md-12">
				           <div class="form-group">
				                <button type="button" class="btn waves-effect waves-light btn-info get-otp" value="exit" name="save"> <i class="fa fa-check"></i> Send Otp</button>
				            </div>
				        </div>
				        <div class="col-md-6 otpbox" style="display:none;">
				           <div class="form-group @if($errors->has('otp'))has-danger @endif">
				                <label class="control-label">OTP</label>
				                <?=Form::text('otp', old('otp'), ['class' => 'form-control', 'placeholder' => 'Enter otp'])?>
				                <span class='text-danger error'>{{ $errors->first('otp') }}</span>
				            </div>
				        </div>
				    </div>
					<div class="row p-t-20">
					</div>
				    <!--/row-->
					<div class="form-actions">
					    <button type="submit" class="btn btn-success save" value="exit" name="save" disabled> <i class="fa fa-check"></i> Save</button>
					    <a data-showloading="yes" href="{{route('account.index')}}" class="btn btn-inverse">Cancel</a>
					</div>
                    <?=Form::close();?>
                </div>
            </div>
        </div>
    </div>
</div>
@stop

@section('css')
    <link rel="stylesheet" type="text/css" href="{{asset('backend/plugins/dropify/dist/css/dropify.min.css')}}">
@stop

@section('script')
    <script src="{{asset('/backend/plugins/dropify/dist/js/dropify.min.js')}}"></script>
    <script src = "https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>

<script type="text/javascript">
	$.ajaxSetup({
        headers: {
            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
        }
    });
	$(document).on('click','.get-otp', function(e) {

		e.preventDefault();
   
        var mobile = $("input[name=mobile]").val();
        var email = $("input[name=email]").val();
   
        $.ajax({
            type:'POST',
       		url:"{{ route('get.otp') }}",
            data:{mobile:mobile, email:email},
            beforeSend : function() {
            	$('.preloader').css({'display': 'block', 'opacity': '0.5'});
        	},
            success:function(data){
              	if(data.success) {
              		$(".hiddenID").val(data.data.id)
              		$('.otpbox').show();
              		$('.get-otp').prop('disabled', true);
              		$('.save').prop('disabled', false);
              		alert("Sent otp successfully!");
              	}
            },
            complete: function() {
  	 			$('.preloader').css({'display': 'none', 'opacity': '1'});
    		},
        });
		
	});
	var show = "{{$show}}";
	if(show){
		$('.otpbox').show();
              		$('.get-otp').prop('disabled', true);
              		$('.save').prop('disabled', false);
	}
</script>
@include('admin.layouts.alert')
@stop

resources/views/admin/accounts/index.blade.php
@extends('admin.layouts.layout')
@section('content')
<div class="row page-titles">
    <div class="col-md-5 align-self-center">
        <h3 class="text-themecolor">Account</h3>
    </div>
    <div class="col-md-7 align-self-center">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="javascript:void(0)">Home</a></li>
            <li class="breadcrumb-item active">list</li>
        </ol>
    </div>
</div>
<div class="container-fluid">
    <!-- ============================================================== -->
    <!-- Start Page Content -->
    <!-- ============================================================== -->
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <div class="card">
                        <div class="card-body">
                        <div class="text-right">
                            <a href="{{route('export')}}" class="btn waves-effect waves-light btn-info" title="Add New">Export Excel</a>
                            <a href="{{route('import-view')}}" class="btn waves-effect waves-light btn-info" title="Add New">Import Excel</a>
                             <a href="{{route('account.create')}}" class="btn waves-effect waves-light btn-info" title="Add New">Add New</a>
                        </div>
                        <div class="table-responsive m-t-20">
                        <table id="master_table" class="table table-bordered table-striped data-table">
                            <thead>
                                <tr>
                                    <th>No</th>
                                    <th>Name</th>
                                    <th>Phone</th>
                                    <th>Agent</th>
                                    <th>Verify</th>
                                    <th>Status</th>
                                    <th>Payment</th>
                                    <th>Created</th>
                                    <th width="100px">Action</th>
                                </tr>
                            </thead>
                        </table>
                        </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@stop
@section('modal')
    <div class="modal fade" id="editPeopleProPreferencesModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel1">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
            </div>
        </div>
    </div>
    <div class="modal fade" id="editPaymentReminderModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel1">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
            </div>
        </div>
    </div>
@stop
@section('script')
<script src="{{asset('/backend/js/plugins/jquery.dataTables.min.js')}}"></script>
<script src="{{asset('/backend/js/plugins/jquery.dataTables.min.js')}}"></script>
<script src="{{asset('backend/js/delete_script.js')}}"></script>
<script src="{{asset('backend/plugins/sweetalert/sweetalert.min.js')}}"></script>
<script src="{{asset('backend/js/fnStandingRedraw.js')}}"></script>
<script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<!-- public/backend/plugins/sweetalert -->
<script type="text/javascript">
$(function () {
    
    var table = $('.data-table').DataTable({
        processing: true,
        serverSide: true,
        ajax: "{{ route('account.index') }}",
        columns: [
            {data: 'id', name: 'id'},
            {data: 'name', name: 'name'},
            {data: 'mobile', name: 'mobile'},
            {data: 'agent_name', name: 'agent_name'},
            {data: 'verify', name: 'verify'},
            {data: 'status', name: 'status'},
            {data: 'payment_status', name: 'payment_status'},
            {data: 'created_at', name: 'created_at'},
            {data: 'action', name: 'action', orderable: false, searchable: false},
        ]
    });
    
  });

$(document).on("click", ".update_payment_status", function(e){
        $('#editPeopleProPreferencesModal .modal-content').html(""); 
        acc_id = $(this).data('account_id');
        $.ajax({
            method: "GET",
            headers: {
                Accept: "application/json"
            },
            url: "{{ route('payment.status.get') }}",
            data: {
                "_token": "{{ csrf_token() }}",
                "account_id": acc_id
            },
            success:  function(result) { 
                if (result.html) {
                    $('#editPeopleProPreferencesModal .modal-content').html(result.html);
                    $('#editPeopleProPreferencesModal').modal('show');
                } 
            }
        })
    });
    $(document).on('submit', '#update_preferences_people_post', function(e){
        e.preventDefault();
        let formData = $(this).serializeArray();
        $.ajax({
            method: "POST",
            headers: {'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')},
            url: "{{ route('payment.status.post') }}",
            data: formData,
            success:  function(result) { 
                if (result.success) {
                    $('#editPaymentReminderModal').modal('hide');
                    window.location.reload();
                } 
            }
        })
    });

    $(document).on("click", ".revise_payment_notify", function(e){
        $('#editPaymentReminderModal .modal-content').html(""); 
        acc_id = $(this).data('account_id');
        $.ajax({
            method: "GET",
            headers: {
                Accept: "application/json"
            },
            url: "{{ route('revise.paymentnotify.get') }}",
            data: {
                "_token": "{{ csrf_token() }}",
                "account_id": acc_id
            },
            success:  function(result) { 
                if (result.html) {
                    $('#editPaymentReminderModal .modal-content').html(result.html);
                    $('#editPaymentReminderModal').modal('show');
                } 
            }
        })
    });
    $(document).on('submit', '#revise_payment_post', function(e){
        e.preventDefault();
        let formData = $(this).serializeArray();
        $.ajax({
            method: "POST",
            headers: {'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')},
            url: "{{ route('revise.payment.notify.post') }}",
            data: formData,
            success:  function(result) { 
                if (result.success) {
                    $('#editPaymentReminderModal').modal('hide');
                    window.location.reload();
                } 
            }
        })
    });


    function deleteacc(id) {
        Swal.fire({
          title: 'Are you sure?',
          text: "You won't be able to revert this!",
          icon: 'warning',
          showCancelButton: true,
          confirmButtonColor: '#3085d6',
          cancelButtonColor: '#d33',
          confirmButtonText: 'Yes, delete it!'
        }).then((result) => {
          if (result.isConfirmed) {
            $.ajax({
                method: "delete",
                headers: {'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')},
                url: "{{ route('account.delete') }}",
                data: {id:id},
                success:  function(result) { 
                    if (result.success) {
                        $('#editPaymentReminderModal').modal('hide');
                        window.location.reload();
                    } 
                }
            })
            Swal.fire(
              'Deleted!',
              'Your file has been deleted.',
              'success'
            )
          }
        })
    }

</script>
@include('admin.layouts.alert')
@stop

<!-- 
<!DOCTYPE html>
<html>
<head>
    <title>Laravel 8 Datatables Tutorial - ItSolutionStuff.com</title>
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css" />
    <link href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css" rel="stylesheet">
    <link href="https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap4.min.css" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.js"></script>  
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.0/jquery.validate.js"></script>
    <script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap4.min.js"></script>
</head>
<body>
    
<div class="container">
    <h1>Laravel 8 Datatables Tutorial <br/> ItSolutionStuff.com</h1>
    <table class="table table-bordered data-table">
        <thead>
            <tr>
                <th>No</th>
                <th>Name</th>
                <th>Email</th>
                <th width="100px">Action</th>
            </tr>
        </thead>
        <tbody>
        </tbody>
    </table>
</div>
   
</body>
   
<script type="text/javascript">
  $(function () {
    
    var table = $('.data-table').DataTable({
        processing: true,
        serverSide: true,
        ajax: "{{ route('users.index') }}",
        columns: [
            {data: 'id', name: 'id'},
            {data: 'name', name: 'name'},
            {data: 'email', name: 'email'},
            {data: 'action', name: 'action', orderable: false, searchable: false},
        ]
    });
    
  });
</script>
</html> -->